Modified prettier configuration and ran on the codebase
buildwithgrove/portal-api pull request #136
Opened 2021-07-08 19:31 UTC by rem1niscence

The prettier configuration, although set up on the project, never actually ran as was supposed to be intended, this was due to two reasons:

* The file was incorrectly place on the project (inside the `pocket-gateway` folder) when the [configuration docs](https://prettier.io/docs/en/configuration.html) states that the checked files look **up** a prettier configuration file, as this was isolated on the `pocket-gateway` folder, any file found it and instead a default configuration of prettier was being ran.
* The command `npm run prettier:fix` was internally running a loopback configuration of prettier, which ignored the project's `prettier` and `.prettierignore` so not even placing the prettier config at root would solve the problem.

The fix was to move the prettier files to root and change the npm script to run the native's prettier command, after that the command was ran and applied all the code style changes. Leading to this **HUGE** PR which practically touches all the files, think of this as the first time prettier was actually ran.

This kinda touches on the issue #124 but only on the prettify code, doesn't refactor any functionality by destructuring or any other technique, I didn't do that as this PR is already way too big as it is right now. Will do it on a separate PR.

2021-07-08 22:34 UTC, nymd requested changes

2021-07-08 22:34 UTC, nymd commented on .prettierrc
> +  "arrowParens": "always"
120 line length pls

2021-07-08 22:38 UTC, rem1niscence commented on .prettierrc
> +  "arrowParens": "always"
added

2021-07-09 00:20 UTC, nymd approved these changes

2021-07-09 00:20 UTC, merged