feat: set blocks range limit on eth_getLogs calls
buildwithgrove/portal-api pull request #174
Opened 2021-07-21 21:32 UTC by crisog

Solves #62.

2021-07-22 19:57 UTC, rem1niscence commented on src/services/pocket-relayer.ts
> +        (toBlock === 'latest' || toBlock === undefined || fromBlock === 'latest' || fromBlock === undefined) &&
this is hard to read, you could separate these into variables like `toBlockValid` checking them separately so at the end end on the else if you only do a simpler check like `!toBlockValid && !fromBlockValid`

2021-07-29 14:56 UTC, crisog commented
Waiting for pocket relayer mock to include tests, @rem1niscence is working on it.

2021-08-16 20:06 UTC, nymd requested changes
Looks good, just a few minor things.

2021-08-16 20:06 UTC, nymd commented on src/application.ts
> +    const defaultLogLimitBlocks: number = parseInt(LOG_LIMIT_BLOCKS) || -1
if the const is 'defaultLogLimitBlocks' then please make the ENV:

DEFAULT_LOG_LIMIT_BLOCKS

2021-08-16 20:06 UTC, nymd commented on src/services/pocket-relayer.ts
> +      if (altruistUrl !== 'undefined') {
Can we only make this check if necessary?  Only if 'latest' is used as a variable. It seems we don't need this call if we know the block numbers already.

2021-08-16 20:06 UTC, nymd commented on src/utils/block.ts
> +export function blockHexToDecimal(hex: string): number {
I think there are some instances of this code in sync-checker that could be removed and instead use this central util?

2021-08-17 14:40 UTC, rem1niscence requested changes

2021-08-17 14:40 UTC, rem1niscence commented on src/errors/limit-error.ts
> +/**
this file in general could have its name changed to `types.ts` and have the limit error type and any upcoming error type that might arise in the future

2021-08-17 17:09 UTC, nymd approved these changes

2021-08-17 17:25 UTC, rem1niscence approved these changes

2021-08-17 18:11 UTC, merged