Feat: Cache overruning session stake session nodes
buildwithgrove/portal-api pull request #268
Opened 2021-09-10 18:44 UTC by rem1niscence

Closes #262. This adds another cache layer to session nodes, now, when a session is created/obtained, a cache is created for the maximum time of the session as set on the pocket configuration. From there on, if within a session a node fails due to overruning their max stake, it will be added to the session's cache and won't be include in future checks (sync and chain check), if a session has no nodes left, it will directly go to the altruists.

This change adds some important changes to take into consideration:

1. On sync check, when penalizing nodes out of sync, is based on the number of nodes available, not 5 nodes as it previously was
2. On chain check, when penalizing nodes reporting incorrect data, is based on the number of nodes available, not 5 nodes as it previously was
3. Sync check only occurs now if there's at least 3 nodes available

Besides that, no other major change was added, but feel free to comment on desired/expected behaviors from this.

2021-09-10 19:31 UTC, nymd requested changes

2021-09-10 19:31 UTC, nymd commented on src/services/pocket-relayer.ts
> +      const cachedRemovedSessionNodes = await this.redis.get(`session-${pocketSession.sessionKey}`)
This is a good trick. I forgot pocket-js already had the concept of a sessionKey.

2021-09-10 19:31 UTC, nymd commented on src/services/pocket-relayer.ts
> +        // Maximum time in milliseconds for the next session to be rolloved,
* to be rolled over

I was a bit concerned about using the session length for anything given that block timing is variable. Optimal block timing is 15 minutes but sometimes they take up to 18 minutes.

I'm not sure we need to set this TTL with any sort of specificity. What's the harm if we set it for 2 hours?  It won't be pulled up if the sessionKey changes.

2021-09-10 19:31 UTC, nymd commented on src/services/sync-checker.ts
> +        this.updateConfigurationConsensus(pocketConfiguration, nodes.length),
This should not change the consensus node count. As you are sending a completely new relay and not specifying what node to send it to, PocketJS will use its own interpretation of what the session is and that includes all 5 nodes.

2021-09-10 19:31 UTC, nymd commented on src/services/sync-checker.ts
> +      consensusNodeCount,
So this should go back to 5.

2021-09-10 19:31 UTC, nymd commented on src/services/chain-checker.ts
> +      consensusNodeCount,
Same as in other check, this should remain 5.

2021-09-10 21:53 UTC, nymd approved these changes

2021-09-13 17:34 UTC, crisog approved these changes

2021-09-15 17:29 UTC, nymd approved these changes

2021-09-15 17:30 UTC, merged