Local Development Environment For The Gateway
buildwithgrove/portal-api pull request #67
Opened 2021-06-09 20:34 UTC by derrandz

2021-06-24 17:01 UTC, nymd requested changes

2021-06-24 17:01 UTC, nymd commented on .github/workflows/staging-us-west-2.yml
> +    branches: [ master ]
this should remain off

2021-06-24 17:04 UTC, derrandz commented on .github/workflows/staging-us-west-2.yml
> +    branches: [ master ]
but we want to deploy to staging right?

2021-06-24 23:57 UTC, nymd requested changes

2021-06-24 23:57 UTC, nymd commented on .github/workflows/testnet.yml
> +    branches: [ staging ]
this should be branches: [ testnet ] 
or something. There is a real testnet deployment that uses pocket testnet and replicates the production setup.

I don't want this deployment to receive staging code unless we purposefully want it there.

2021-06-25 00:04 UTC, nymd approved these changes

2021-06-25 00:06 UTC, merged