fix: update dispatchers urls
buildwithgrove/portal-api pull request #827
Opened 2022-04-25 16:49 UTC by PseudoMera

2022-04-25 16:54 UTC, rem1niscence approved these changes

2022-04-25 16:54 UTC, nymd requested changes
What you have will work but since it is hitting 4201 it will always go to testnet-1

2022-04-25 16:54 UTC, nymd commented on .github/workflows/testnet-us-west-2.yml
> +          envkey_DISPATCH_URL: https://testnet-1.nodes.pokt.network:4201,https://testnet-2.nodes.pokt.network:4201,https://testnet-3.nodes.pokt.network:4201
ports need to increment with the node number,so its

testnet-2, port 4202, etc

2022-04-25 16:58 UTC, nymd approved these changes

2022-06-21 14:44 UTC, rem1niscence approved these changes

2022-06-21 14:45 UTC, merged