Gateway host env
buildwithgrove/portal-api pull request #984
Opened 2022-11-14 15:36 UTC by rem1niscence

move gateway host string to an environment variable

2022-11-14 20:33 UTC, adshmh requested changes
Could we add tests to cover both valid and invalid sub-domain sceanrios?

2022-11-14 20:33 UTC, adshmh commented on tests/acceptance/v1.controller.acceptance.ts
> +    it('invokes POST /v1/{appId} and successfully relays a request only through the altruist', async () => {
This doesn't related to this PR, could you clarify why it is needed?

2022-11-14 20:42 UTC, crisog submitted a review, later dismissed
Looks good, straight forward 👍🏽 

If #977 gets merged, this ENV won't be needed in the future so I'll add a note in there.

2022-11-15 17:03 UTC, adshmh approved these changes
LGTM. Thanks!

2022-11-15 17:56 UTC, merged